name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v20

      - uses: cachix/cachix-action@v2
        with:
          name: ocamljvm
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - run: nix build

      - run: nix develop

      - name: exec HelloWorld
        run: dune exec ocaml_jvm java_src/HelloWorld.class

      - name: exec FizzBuzz
        run: dune exec ocaml_jvm java_src/FizzBuzz.class
