name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install opam
        run: |
          sudo add-apt-repository ppa:avsm/ppa
          sudo apt update
          sudo apt install opam

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: _opam
          key: opam-${{ hashFiles('ocaml_jvm.opam') }}
          restore-keys: opam-

      - name: opam init (use cache)
        continue-on-error: true
        run: |
          opam init --auto-setup --bare --enable-shell-hook
          opam switch create . --no-install 5.0.0~beta1

      - name: opam install (use cache)
        run: |
          opam install . --deps-only --yes

      - name: exec HelloWorld
        run: opam exec -- dune exec ocaml_jvm java_src/HelloWorld.class

      - name: exec FizzBuzz
        run: opam exec -- dune exec ocaml_jvm java_src/FizzBuzz.class
