name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: install opam
        run: |
          sudo add-apt-repository ppa:avsm/ppa
          sudo apt update
          sudo apt install opam

      - run: opam install . --deps-only
      - run: opam exec -- dune build
