name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - run: add-apt-repository ppa:avsm/ppa
      - run: apt update
      - run: apt install opam

      - run: opam install . --deps-only
      - run: opam exec -- dune build
